# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER procon

# 挂载目录
VOLUME /home/procon
# 创建目录
RUN mkdir -p /home/procon
# 指定路径
WORKDIR /home/procon
# 复制jar文件到路径
COPY ./jar/procon-gateway.jar /home/procon/procon-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","procon-gateway.jar"]
