# 基础镜像
FROM redis
# author
MAINTAINER procon

# 挂载目录
VOLUME /home/procon/redis
# 创建目录
RUN mkdir -p /home/procon/redis
# 指定路径
WORKDIR /home/procon/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/procon/redis/redis.conf
