# 基础镜像
FROM apache/skywalking-java-agent:8.8.0-java8
# author
MAINTAINER procon
ARG JAR_FILE
COPY ${JAR_FILE} /monitor-service.jar
EXPOSE 9400
# 启动定时任务服务
ENTRYPOINT ["java","-jar","/monitor-service.jar"]
